name: Backport merged pull request

on:
  workflow_dispatch:
#  pull_request:
#    types: [closed]
#  issue_comment:
#    types: [created]

jobs:
  call-reusable-flow:
    uses: camunda/automation-platform-github-actions/.github/workflows/backport.yml@main
    secrets: inherit
