name: "Publish to Maven Central"

env:
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  CI_GPG_PASSPHRASE: ${{ secrets.CI_GPG_PASSPHRASE }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

# pull_request condition added temporarily to test the workflow
# once verified, it shall be removed
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-central:
    name: Publish to Maven Central
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        #added with option due to runner checking out a detached HEAD state in prepare step
        with:
          token: ${{ secrets.GITHUB_TOKEN }}                    # or use default GITHUB_TOKEN
          persist-credentials: true             # allow git push from the job
          fetch-depth: 0                        # full history so branch refs exist
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}          # checkout the branch (not a detached SHA)

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          server-id: ossrh
          server-username: CI_DEPLOY_USERNAME
          server-password: CI_DEPLOY_PASSWORD
          gpg-private-key: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          gpg-passphrase: CI_GPG_PASSPHRASE

      - name: Configure git
        uses: ./.github/actions/configure-git

      - name: Download deps and plugins
        run: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies -s ./settings.xml

      - name: Configure GitHub authentication for Maven Release Plugin
        run: |
          git config --global url."https://${GH_TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Prepare release
        run: mvn -B -DpreparationGoals=clean release:prepare -Psonatype-oss-release,distro,distro-ce,distro-tomcat,distro-webjar,distro-run -DskipTests=true -DignoreSnapshots=true -DinteractiveMode=false

      - name: Perform release
        run: mvn -B release:perform -Psonatype-oss-release,distro,distro-ce,distro-tomcat,distro-webjar,distro-run -DskipTests=true -DinteractiveMode=false
