name: Synchronize label colors

on:
  workflow_dispatch:
#  label:
#    types:
#      - created

jobs:
  call-reusable-flow:
    uses: camunda/automation-platform-github-actions/.github/workflows/sync-label-colors.yml@main    
